### ISSUE TITLE
frame rate issue with the .mkv file dumped by FileFrameFilter (lesson_1_c.py)

### ISSUE THREAD

**Issue by wkelongws** [elsampsa/valkka-examples#1]
I have a IP camera which output 1080x1920 @ 30 fps. below is the codec infomation of the rtsp stream from VLC:
![1](https://user-images.githubusercontent.com/14045078/56912174-95db6200-6a63-11e9-9d6e-333fb3f73f82.png)
I tied to record a short video clip of the rtsp stream using FileFrameFilter in lesson_1_c.py, and below are the codec info of the recorded clips from both vlc and file properties (by right click):
![3](https://user-images.githubusercontent.com/14045078/56912447-20bc5c80-6a64-11e9-8d84-0739eeec581b.png)

![2](https://user-images.githubusercontent.com/14045078/56912455-244fe380-6a64-11e9-87f2-3a3f7cfe84e0.png)

To me it looks like the proper frame rate information got lost during the file dumping process. The recorded video clip plays (in normal fps visually) by have some visual artifacts (freezes and blurs).

I have tried two other rtsp streams (from a wowza video server) with full HD @ 10fps as well. The recorded clips have the same frame rate issue (N/A in vlc codec and 1000fps in properties) and stronger visual artifacts. 

All three streams tried above can be record perfectly using ffmpeg.

And could be due to the same timestamp issue (guessing), the seeking and pausing (especially seeking) when playing the recorded clips doesn't work as a charm in lesson_6_a.py and lesson_6_a_read.py as well.

What could be the issue here? Thanks.

**Comment by eranpet** [comment]
looks like there is a bug in the FileFrameFIlter.  will look into this this week.

**Comment by elsampsa** [comment]
The following things should be implemented to FileFrameFilter
1. count number of frames & bytes
2. rewrite the .mkv file header once we're done with writing

(1) is trivial, but there is no f-way to get (2) to work

At this point it's still ok to write the header:

https://github.com/elsampsa/valkka-core/blob/master/src/fileframefilter.cpp#L220

But here it isn't effective anymore:

https://github.com/elsampsa/valkka-core/blob/master/src/fileframefilter.cpp#L293

This bug is cosmetic, not functional and I believe @eranpet has no time for this at the moment, right?

@wkelongws if you wan't to contribute, it would be great!  :)
