### ISSUE TITLE
Pull h264 frames no decoding

### ISSUE THREAD

**Issue by bobbych** [elsampsa/valkka-examples#6]
## General Question

I am trying to get H264 raw frames from rtsp stream without decoding to feed to a different python process. I was following example [here](https://github.com/elsampsa/valkka-examples/blob/master/api_level_1/cli/shmem_test_encoded.py)   Streaming seems to be working fine on the server side, but running into below error on the client side.

```
registering stream
playing stream !
Getting shmem buffers
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "stream_encode.py", line 38, in client
    shmem_list.append(getNumpyShmem(rb,i))
  File "/usr/lib/python3/dist-packages/valkka/core/valkka_core.py", line 427, in getNumpyShmem
    return _valkka_core.getNumpyShmem(rb, i)
TypeError: in method 'getNumpyShmem', argument 1 of type 'SharedMemRingBufferRGB *'
```

my understanding is, if we use `SharedMemRingBufferRGB` we are essentially decoding image at that point? is there a way to just get raw packets without decoding on python side >

Thanks

**Comment by bobbych** [comment]
I was able to get his working by using `ShmemClient`. I now get 3 numpy arrays/payload per frame. How can I decode these frames using opencv or pyav

**Comment by elsampsa** [comment]
In order to know - what you are doing, and for yourself to know what you are doing, please provide a filtergraph, where we can see the running threads and filters (please refer to the tutorial what a "filtergraph" is): at the moment I am not sure what you are feeding to shared memory => what you are receiving at the python side.

I'd imagine that your best shot would be to receive frag-mp4 from libValkka via shared memory and feed *that* to OpenCV video decoder.

And what is the motivation to decode the image at the python/opencv side and not let libValkka do this?

**Comment by bobbych** [comment]
I am using below filter chain
```
(LiveThread) --> {ShmemFrameFilter}
```

I also tried using 

```
(LiveThread:livethread) --> {FragMP4ShmemFrameFilter} --> {FragMP4MuxFrameFilter}
```

On the client side when I am  trying decode packets with opencv `imdecode` method with no luck.

Main reason for deferring decoding to later has to do with available compute at the streaming machine

**Comment by elsampsa** [comment]
Feeding from ``LiveThread`` directly to ``ShmemFrameFilter`` **is not advised** anywhere in the tutorial.  However, it seems you _can_ do this (!)  In this case you will then simply get raw H264 packets at the python client side.   You were wondering about those numpy arrays you get: they must simply be the SPS and PPS packets and the I Frame (what are these?  google is your friend).  

Next, let's see what you are trying to do with all those raw H264 video stream packets.

If you take a look at opencv's ``imdecode`` function in [here](https://docs.opencv.org/3.4/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56), you can see that it only understands static image formats.  It is not supposed to decode video formats, such as H264.

I don't think there is any function in opencv where you could stuff in H264 video segments and then get decoded images.  Even if there was, I don't know why anyone should do that.  On the other hand if you decode in libValkka side (as in the tutorial), then you can take advantage of multithreading (because libValkka runs in background), something you couldn't do in python.

I also don't understand what you mean with "Main reason for deferring decoding to later has to do with available compute at the streaming machine".  You want to stream the H264 segments in some machine (a) and then send them into some other linux box (b)  and do the decoding there.  Why don't you just receive the RTSP source in (b) directly?

There are too many things here which I do not understand, so I will close this ticket.

I suggest that you go through the tutorial and additionally study the following subjects (google is your friend): RTSP, RTP, H264.

**Comment by bobbych** [comment]
thanks for your help. I just want to close loop on what I meant by not having enough compute to decode. Basically device at the edge is not capable of decoding and device that is capable of decoding does not have direct access to camera. Unfortunately we have to work with this situation. my idea was to receive packets and do decoding on gpu and further pipeline it for inference on several models. Hope that makes sense

**Comment by elsampsa** [comment]
This is your use case?
```

RTSP camera  <-----> edge device (rasbpi or similar)   
                                       |
                                       +  ----> internet ----->  Cloud Service      
                                                              - decode frames
                                                              - do inference on images
```
You _can_ actually do (most of) this with libValkka:

- At your edge device,  receive frag-mp4 packets from the RTSP camera at the python side
- Still on your edge device, create a python-based websocket server (or something similar)
- Serve from that websocket the frag-mp4 packets
- Receive the frag-mp4 packets in the cloud (again, you can create a python client for this)

There is even an example project how to do all that.  You can start investigating from [here](https://elsampsa.github.io/valkka-examples/_build/html/cloud.html) 

So, now you are receiving the H264 video packets, encapsulated as frag-mp4 in the cloud.  You still have to decode them.

You still have the problem of finding a decoder that has a python interface.  The opencv videocapture class could solve you this problem (cv2.VideoCapture), but unfortunately you can't provide it packets "manually" (i.e. call function(bytes) and then it would return you frames when these are ready).  Instead you can just initialize it with an address.  You could do a hack by creating a (local) tcp server serving those same frag-mp4 packets and then just do ``cv2.VideoCapture("tcp://host:port")``.

I am starting to think that a nice project would be to implement the demuxing frag-mp4 in libValkka.. then that mentioned decoding in python in the cloud could be done with libValkka (in the lack of sponsors, not sure when I would do this though..)

And then there is also yet another possibility:
- Create an ssh tunnel from the edge device to the cloud host
- ..then in the cloud host you can just access the "rtsp://" address of the camera as it was in the cloud host (with cv2.VideoCapture or even with libValkka)
- in this case, you _must_ request tcp streaming (instead of udp streaming) from the camera

Hope this helps.
